# Generated by Django 5.1.1 on 2024-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hashtag_file_description_file_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='hashtags',
            field=models.ManyToManyField(related_name='files', to='user.hashtag'),
        ),
    ]
